title: Jeremy的技术博客
description: 学习  总结  分享  提升
show_downloads: true

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jeremyliao.github.io/" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Jeremy"
image: /thumbnail-jumbo.png
twitter:
facebook:
